### ISSUE TITLE
Speed direction needs to be negative

### ISSUE THREAD

**Issue by tdkemp** [Bonelab/Wolff#11]
@Besler I think we should switch this sign, as well as for test_negative_model_inside_is_positive() & test_negative_model_with_spacing(). We'll have to update the assertAlmostEqual also. If you want I can make the changes. I think it should be fixed in both the test_advection_model.py & test_mean_curvature_model.py

Edit: I think the advection test is correct, we should modify the mean curvature test.

https://github.com/Bonelab/Wolff/blob/1eabd11db5f106745f17d2d608c8b83ae0d560bf/tests/models/test_advection_model.py#L79

**Comment by Besler** [comment]
I checked this pretty close. Can you run the [propogation example](https://github.com/Bonelab/Wolff/blob/master/examples/constant_propagation.py) and see what you get?

**Comment by Besler** [comment]
Wait, I understand now. I checked the propogation model well but not the advection model. I had assumed "up" as positive, but it might not be. Okay good point.
